export type Course = { slug: string; number: string; title: string; summary: string; project: string; weeks: string; modules: string[]; brief: string[] };
export const core: Course[] = [
  { slug: 'web-and-workstation', number: '01', title: 'Web and workstation', summary: 'Understand the machine, the terminal, Git, the browser, the web, and the habits that make independent work possible.', project: 'A documented field notebook', weeks: 'Weeks 01–02', modules: ['How the web works', 'Terminal and files', 'Git and GitHub', 'Debugging from evidence'], brief: ['Create a repository with a first commit.', 'Write setup steps another learner can follow.', 'Record one failed command and how you diagnosed it.', 'Submit the repository, gist, and self-review.'] },
  { slug: 'ui-foundations', number: '02', title: 'UI and UX foundations', summary: 'Move from a problem to a usable interface. Learn hierarchy, flows, wireframes, accessibility, responsive layout, and visual systems.', project: 'A tested service flow in Figma and HTML', weeks: 'Weeks 03–04', modules: ['User, problem, and task', 'Flows and wireframes', 'Semantic HTML and accessible forms', 'CSS layout and responsive behavior'], brief: ['Map one user task before designing the screen.', 'Create a Figma flow and a responsive implementation.', 'Test the form with a keyboard-only pass.', 'Document one design decision and one change after testing.'] },
  { slug: 'javascript-thinking', number: '03', title: 'Programming with JavaScript', summary: 'Use variables, functions, data structures, modules, events, state, async work, and tests to model behavior.', project: 'A browser tool with tests', weeks: 'Weeks 05–07', modules: ['Values, functions, and data', 'DOM and events', 'State and async work', 'Tests and edge cases'], brief: ['Build a small tool for a real task.', 'Write tests for the behavior that matters.', 'Keep a note for one unsupported case.', 'Explain the data flow from input to result.'] },
  { slug: 'systems-and-data', number: '04', title: 'Systems and data', summary: 'Connect a client to a server. Learn HTTP, APIs, validation, relational data, authentication concepts, logs, and deployment.', project: 'A full-stack product slice', weeks: 'Weeks 08–10', modules: ['Client and server boundaries', 'HTTP and API contracts', 'Data and validation', 'Deploy, observe, and recover'], brief: ['Choose one narrow product action.', 'Draw the request path before implementing it.', 'Handle one failure path clearly.', 'Ship a URL with a README and rollback note.'] },
  { slug: 'working-with-others', number: '05', title: 'Working with others', summary: 'Read an unfamiliar codebase, review a change, plan a sprint, refactor safely, and leave context for the next person.', project: 'A reviewed maintenance release', weeks: 'Weeks 11–12', modules: ['Issues and one-week sprints', 'Pull requests and review', 'Refactoring and risk', 'Technical writing and handoff'], brief: ['Take a small issue from brief to merge.', 'Open a reviewable pull request.', 'Write a release note and risk note.', 'Complete the core self-review before choosing a track.'] },
];
export const tracks = [
  { slug: 'full-stack-javascript', title: 'Full-Stack JavaScript + TypeScript', duration: '8 weeks + 4-week team build', tone: 'Browser to backend, typed contracts, and production habits.', courses: ['Advanced UI systems', 'TypeScript and shared contracts', 'React applications', 'Node services and PostgreSQL', 'Testing, auth, and deployment'], capstone: 'A personal product built from a Frontend Mentor brief or an approved original brief.' },
  { slug: 'ruby', title: 'Ruby and Rails', duration: '8 weeks + 4-week team build', tone: 'Ruby fluency, Rails conventions, data modeling, and dependable web products.', courses: ['Ruby programming', 'Rails and MVC', 'Active Record and SQL', 'Auth, APIs, and testing', 'Deploy and maintain'], capstone: 'A personal Rails product with a written technical case study.' },
  { slug: 'mobile', title: 'Mobile with React Native', duration: '8 weeks + 4-week team build', tone: 'TypeScript, mobile interaction, device capabilities, offline behavior, and release discipline.', courses: ['React Native foundations', 'Navigation and state', 'Forms, storage, and APIs', 'Native capabilities and accessibility', 'Testing and release'], capstone: 'A personal mobile app with a tested primary flow.' },
];
export const practice = { technical: ['Debugging unfamiliar systems', 'Git and code review', 'Testing strategy', 'HTTP and API diagnosis', 'Security basics', 'Logs and observability', 'Documentation and handoff', 'Deployment and rollback'], professional: ['Daily check-in writing', 'Weekly sprint planning', 'Giving and receiving review', 'Estimating uncertainty', 'Communicating blockers', 'Technical presentations', 'Portfolio case study', 'Interview practice'] };
