export type Course = { slug: string; number: string; title: string; summary: string; project: string; weeks: string; modules: string[]; brief: string[] };
export const core: Course[] = [
  { slug: 'web-and-workstation', number: '01', title: 'Web and workstation', summary: 'Understand the machine, the terminal, Git, the browser, the web, and the habits that make independent work possible.', project: 'A documented field notebook', weeks: 'Weeks 01–02', modules: ['How the web works', 'Terminal and files', 'Git and GitHub', 'Debugging from evidence'], brief: ['Create a repository with a first commit.', 'Write setup steps another learner can follow.', 'Record one failed command and how you diagnosed it.', 'Submit the repository, gist, and self-review.'] },
  { slug: 'ui-foundations', number: '02', title: 'UI and UX foundations', summary: 'Move from a problem to a usable interface. Learn hierarchy, flows, wireframes, accessibility, responsive layout, and visual systems.', project: 'A tested service flow in Figma and HTML', weeks: 'Weeks 03–04', modules: ['User, problem, and task', 'Flows and wireframes', 'Semantic HTML and accessible forms', 'CSS layout and responsive behavior'], brief: ['Map one user task before designing the screen.', 'Create a Figma flow and a responsive implementation.', 'Test the form with a keyboard-only pass.', 'Document one design decision and one change after testing.'] },
  { slug: 'javascript-thinking', number: '03', title: 'Programming with JavaScript', summary: 'Use variables, functions, data structures, modules, events, state, async work, and tests to model behavior.', project: 'A browser tool with tests', weeks: 'Weeks 05–07', modules: ['Values, functions, and data', 'DOM and events', 'State and async work', 'Tests and edge cases'], brief: ['Build a small tool for a real task.', 'Write tests for the behavior that matters.', 'Keep a note for one unsupported case.', 'Explain the data flow from input to result.'] },
  { slug: 'systems-and-data', number: '04', title: 'Systems and data', summary: 'Connect a client to a server. Learn HTTP, APIs, validation, relational data, authentication concepts, logs, and deployment.', project: 'A full-stack product slice', weeks: 'Weeks 08–10', modules: ['Client and server boundaries', 'HTTP and API contracts', 'Data and validation', 'Deploy, observe, and recover'], brief: ['Choose one narrow product action.', 'Draw the request path before implementing it.', 'Handle one failure path clearly.', 'Ship a URL with a README and rollback note.'] },
  { slug: 'working-with-others', number: '05', title: 'Working with others', summary: 'Read an unfamiliar codebase, review a change, plan a sprint, refactor safely, and leave context for the next person.', project: 'A reviewed maintenance release', weeks: 'Weeks 11–12', modules: ['Issues and one-week sprints', 'Pull requests and review', 'Refactoring and risk', 'Technical writing and handoff'], brief: ['Take a small issue from brief to merge.', 'Open a reviewable pull request.', 'Write a release note and risk note.', 'Complete the core self-review before choosing a track.'] },
];
export type TrackUnit = { slug: string; title: string; summary: string; lessons: string[]; project: string };
export type Track = { slug: string; title: string; duration: string; tone: string; courses: string[]; outcomes: string[]; units: TrackUnit[]; capstone: string };
export function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }

export const tracks: Track[] = [
  { slug: 'full-stack-javascript', title: 'Full-Stack JavaScript + TypeScript', duration: '8 weeks + 4-week team build', tone: 'Browser to backend, typed contracts, and production habits.', courses: ['Intermediate HTML and CSS', 'JavaScript and browser programming', 'Advanced HTML and CSS', 'React and TypeScript', 'Databases and SQL', 'Node services and APIs', 'Professional delivery'], outcomes: ['Build a typed React application from a product brief.', 'Design and consume a Node API with a relational data model.', 'Ship tested, documented work that another engineer can run.'], units: [
    { slug: 'intermediate-html-css', title: 'Intermediate HTML and CSS', summary: 'Make structure, forms, layout, and responsive behavior deliberate.', lessons: ['Semantic page structure and landmarks', 'Forms, validation, and useful errors', 'CSS units, cascade, and custom properties', 'Grid, Flexbox, and responsive composition'], project: 'Sign-up flow and admin dashboard with a Figma reference, keyboard pass, and responsive README.' },
    { slug: 'javascript-browser', title: 'JavaScript and browser programming', summary: 'Move from syntax to behavior, modules, data, and asynchronous browser work.', lessons: ['Objects, factories, and module boundaries', 'DOM state and event design', 'npm, bundling, and project structure', 'APIs, async work, and request states', 'Testing, linting, and edge cases'], project: 'A tested browser application that consumes a real API and explains its data flow.' },
    { slug: 'advanced-html-css', title: 'Advanced HTML and CSS', summary: 'Build interfaces that hold up across devices, input methods, and content changes.', lessons: ['Animation, transitions, and motion restraint', 'Accessibility and keyboard navigation', 'Responsive images and media', 'Design tokens and visual consistency'], project: 'A responsive product homepage audited for keyboard access, contrast, and narrow screens.' },
    { slug: 'react-typescript', title: 'React and TypeScript', summary: 'Compose a typed interface, manage state, and test the boundaries between components.', lessons: ['Components, props, and JSX', 'State, effects, and data fetching', 'Forms, routing, and application state', 'TypeScript models and shared contracts', 'React testing and maintainable composition'], project: 'A multi-route React product with typed data, tested flows, and a short architecture note.' },
    { slug: 'databases-sql', title: 'Databases and SQL', summary: 'Model relationships and use SQL to make product behavior durable.', lessons: ['Tables, keys, and relationships', 'Queries, joins, and constraints', 'Migrations, seeds, and safe data changes'], project: 'A relational data model with a query notebook and a small feature backed by SQL.' },
    { slug: 'node-services', title: 'Node services and APIs', summary: 'Build the server side with clear HTTP contracts, validation, authentication, and tests.', lessons: ['Node runtime, modules, and environment configuration', 'Express routes, controllers, and error handling', 'PostgreSQL access and ORM trade-offs', 'Authentication, authorization, and secure defaults', 'API design, testing, and deployment'], project: 'A documented service with authentication, a PostgreSQL feature, API tests, and a deployed URL.' },
    { slug: 'professional-delivery', title: 'Professional delivery', summary: 'Package the work so another engineer, mentor, or employer can understand it.', lessons: ['Intermediate Git and reviewable pull requests', 'Technical writing and decision records', 'Portfolio case study and personal website', 'Interview practice and project walkthroughs'], project: 'A personal capstone based on a Frontend Mentor brief or approved original brief, reviewed by a mentor.' },
  ], capstone: 'A personal product built from a Frontend Mentor brief or an approved original brief.' },
  { slug: 'mobile', title: 'Mobile with React Native', duration: '8 weeks + 4-week team build', tone: 'TypeScript, mobile interaction, device capabilities, offline behavior, and release discipline.', courses: ['React Native foundations', 'Navigation and state', 'Forms, storage, and APIs', 'Native capabilities and accessibility', 'Testing and release'], outcomes: ['Build a mobile flow that works on small screens and poor connections.', 'Handle navigation, local storage, network states, and device permissions.', 'Test and document a release candidate.'], units: [
    { slug: 'mobile-foundations', title: 'React Native foundations', summary: 'Learn the platform primitives and build for touch first.', lessons: ['Project setup and platform differences', 'Components, styling, and layout', 'Touch targets, gestures, and keyboard behavior'], project: 'A small multi-screen mobile interface with a documented setup.' },
    { slug: 'mobile-navigation', title: 'Navigation and state', summary: 'Give users a reliable path through the app and make state ownership clear.', lessons: ['Stacks, tabs, and deep links', 'Local state and derived state', 'Loading, empty, and error screens'], project: 'A navigable mobile flow with explicit state diagrams.' },
    { slug: 'mobile-data', title: 'Forms, storage, and APIs', summary: 'Connect mobile input to durable data while respecting unreliable networks.', lessons: ['Accessible mobile forms', 'Storage and persistence', 'API requests and retry behavior'], project: 'An offline-tolerant data entry feature with sync notes.' },
    { slug: 'mobile-native', title: 'Native capabilities and accessibility', summary: 'Use device features with permission, fallback, and inclusive interaction in mind.', lessons: ['Permissions and device APIs', 'Images, location, and notifications', 'Screen readers and accessible gestures'], project: 'A device-aware feature with permission and fallback states.' },
    { slug: 'mobile-release', title: 'Testing and release', summary: 'Verify the primary flow and produce a release candidate someone else can install.', lessons: ['Component and interaction tests', 'Debugging on a real device', 'Release checklist and crash notes'], project: 'A tested release candidate with a short technical case study.' },
  ], capstone: 'A personal mobile app with a tested primary flow.' },
  { slug: 'devops', title: 'DevOps and Cloud Operations', duration: '8 weeks + 4-week team build', tone: 'Reliable delivery, Linux systems, infrastructure as code, observability, and calm incident response.', courses: ['Linux, networking, and shell operations', 'Containers and service boundaries', 'CI/CD pipelines and release safety', 'Cloud infrastructure and infrastructure as code', 'Observability, security, and incident response'], outcomes: ['Explain how an application moves from commit to running service.', 'Build a repeatable deployment pipeline with safe environment handling.', 'Use logs, metrics, and runbooks to diagnose and recover from failure.'], units: [
    { slug: 'linux-networking', title: 'Linux and networking', summary: 'Operate a server from the shell and understand the network paths around a service.', lessons: ['Processes, filesystems, and permissions', 'Shell scripts and repeatable operations', 'DNS, HTTP, ports, and TLS', 'Users, secrets, and least privilege'], project: 'A server setup runbook with a hardened service and a recorded failure investigation.' },
    { slug: 'containers', title: 'Containers and service boundaries', summary: 'Package an application and make its runtime assumptions visible.', lessons: ['Images, layers, and registries', 'Dockerfiles and compose environments', 'Service boundaries and health checks'], project: 'A containerized application with local development and production notes.' },
    { slug: 'ci-cd', title: 'CI/CD and release safety', summary: 'Automate checks and releases without hiding risk behind a green pipeline.', lessons: ['Pipeline stages and quality gates', 'Secrets and environment promotion', 'Deploy previews, rollbacks, and change records'], project: 'A pipeline that tests, builds, deploys, and can roll back a service.' },
    { slug: 'cloud-iac', title: 'Cloud infrastructure and IaC', summary: 'Describe infrastructure as code and make environments reproducible.', lessons: ['Cloud primitives and shared responsibility', 'Infrastructure as code and state', 'Networking, storage, and cost boundaries'], project: 'A reproducible environment with an infrastructure diagram and teardown steps.' },
    { slug: 'observability-security', title: 'Observability and security', summary: 'Know when a service is failing and reduce the blast radius of a mistake.', lessons: ['Logs, metrics, traces, and useful alerts', 'Threat modeling and dependency updates', 'Backups, recovery objectives, and incident notes'], project: 'A service dashboard with alerts, a threat note, and a tested backup restore.' },
  ], capstone: 'A production runbook and deployed service with a pipeline, dashboards, alerts, and a tested recovery path.' },
];
export const practice = { technical: ['Debugging unfamiliar systems', 'Git and code review', 'Testing strategy', 'HTTP and API diagnosis', 'Security basics', 'Logs and observability', 'Documentation and handoff', 'Deployment and rollback'], professional: ['Daily check-in writing', 'Weekly sprint planning', 'Giving and receiving review', 'Estimating uncertainty', 'Communicating blockers', 'Technical presentations', 'Portfolio case study', 'Interview practice'] };
