import Link from 'next/link';
import { tracks } from '@/lib/data';

export default function TracksPage() {
  return <div className="mx-auto w-[min(1160px,calc(100%-32px))] py-16">
    <p className="eyebrow text-coral">After the core / 8 weeks</p>
    <h1 className="mt-4 max-w-5xl text-6xl font-black leading-[.86] tracking-[-.08em] md:text-8xl">Choose the work<br /><span className="text-coral">you want to practice.</span></h1>
    <p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">After the core, choose one track and spend eight weeks building in that environment. Each track ends with a personal capstone and a four-week team product.</p>
    <div className="mt-14 grid gap-5">{tracks.map((track, index) => <article key={track.slug} className="grid gap-8 border border-line bg-panel p-6 dark:border-slate-700 dark:bg-slate-900 lg:grid-cols-[180px_1fr_1fr] lg:p-8"><div><p className="font-mono text-xs text-coral">TRACK 0{index + 1}</p><p className="mt-4 font-mono text-xs text-muted">{track.duration}</p></div><div><h2 className="text-3xl font-black tracking-tight">{track.title}</h2><p className="mt-3 max-w-md text-sm leading-6 text-slate-600 dark:text-slate-300">{track.tone}</p><p className="mt-6 border-t border-line pt-5 text-sm font-bold dark:border-slate-700">Capstone</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{track.capstone}</p><Link href={'/tracks/' + track.slug + '/'} className="mt-6 inline-block text-sm font-bold text-coral">Open units and lessons →</Link></div><div><p className="eyebrow text-coral">{track.units.length} units / {track.units.reduce((sum, unit) => sum + unit.lessons.length, 0)} lessons</p><ol className="mt-4 space-y-3 border-t border-line pt-4 text-sm dark:border-slate-700">{track.units.slice(0, 5).map((unit, unitIndex) => <li key={unit.slug} className="flex gap-3"><span className="font-mono text-xs text-coral">0{unitIndex + 1}</span><span>{unit.title}</span></li>)}</ol>{track.units.length > 5 && <p className="mt-3 text-xs text-muted">+ {track.units.length - 5} more units on the track page</p>}<details className="mt-6 border-t border-line pt-4 dark:border-slate-700"><summary className="cursor-pointer text-sm font-bold">What you should be able to do</summary><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{track.outcomes.map((outcome) => <li key={outcome}>↳ {outcome}</li>)}</ul></details></div></article>)}</div>
    <div className="mt-10 grid gap-5 md:grid-cols-2"><div className="border-l-4 border-coral bg-[#e7f3ee] p-6 dark:bg-slate-800"><p className="eyebrow text-coral">BEFORE YOU FINISH</p><p className="mt-3 text-sm leading-6">Every track includes code review, testing, technical writing, security basics, deployment notes, and a case study you can walk through in an interview.</p></div><div className="border border-line p-6 dark:border-slate-700"><p className="eyebrow text-coral">FOUR-WEEK TEAM PRODUCT</p><p className="mt-3 text-sm leading-6">Five learners choose a problem, design the flow in Figma, write the technical notes, and ship a scoped product with mentor review. <Link href="/method/" className="font-bold underline">See the team process.</Link></p></div></div>
  </div>;
}
